name: Add new issues to related projects

on:
  issues:
    types:
      - opened

jobs:
  add-to-the-overview:
    name: Add issue to the Overview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/LL782/projects/1/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT_LL782_OVERVIEW }}
  add-to-the-mundoko-maps:
    name: Add issue to Mundoko Maps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/LL782/projects/19/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT_LL782_OVERVIEW }}
